import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Orbitron } from 'next/font/google'
import './globals.css'
import TerminalAnimation from "../components/TerminalAnimation"

const orbitron = Orbitron({
  subsets: ['latin'],
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body className={orbitron.className}>

      <div className="background-terminal">
  <TerminalAnimation/>
</div>

      <div className="network-background">

  <div className="packet-bg"></div>
  <div className="packet-bg" style={{animationDelay:"2s"}}></div>
  <div className="packet-bg" style={{animationDelay:"4s"}}></div>
  <div className="packet-bg" style={{animationDelay:"6s"}}></div>

</div>

        {children}
      </body>
    </html>
  );
}
